general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
    ignore_dbus_inhibit = false
}

listener {
    timeout = 60                                 # 1min
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}

listener {
    timeout = 180                                 # 3min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

# Take out this to see if the crashing hyprlock is resolved. I think all displays (including fallback) get disabled by this after 300 seconds and this triggers
# the crash in hyprlock, as there are no remaining displays to render on. It likely also takes down the rest of the OS windows, so even if I got back in, there
# probably wouldn't be much to come back to...
listener {
    timeout = 300                                 # 5.83min
    on-timeout = hyprctl dispatch dpms off        # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on          # screen on when activity is detected after timeout has fired.
}